#!/bin/sh

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

echo '\n\033[1;92mSimulação - malha 20x20.\033[0m\n'
cd m01
./Allrun
cd ..

echo '\n\033[1;92mSimulação - malha 40x40.\033[0m\n'
cd m02 
./Allrun

