#!/bin/sh

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

echo '\n\033[1;92mGeração da geometria e malha com o blockMesh.\033[0m\n'
blockMesh

echo '\033[1;92mSolução do escoamento com o icoFoam.\033[0m\n'
icoFoam > log

echo '\033[1;92mPós-processamento dos resíduos com o foamLog.\033[0m\n'
foamLog log

echo '\033[1;92mGráficos criados usando o gnuplot.\033[0m\n'
gnuplot *.plt

