#!/bin/sh

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

echo '\n\033[1;92mGeração da geometria e malha com o blockMesh.\033[0m\n'
blockMesh

echo '\033[1;92mSolução do escoamento com o simpleFoam.\033[0m\n'
simpleFoam > log

echo '\033[1;92mPós-processamento dos resíduos com o foamLog.\033[0m\n'
foamLog log

echo '\033[1;92mPós-processamento do perfil de velocidade com o postProcess.\033[0m\n'
postProcess -func sampleU

echo '\033[1;92mEdita o arquivo de U em probes.\033[0m\n'
sed -i 's/(//g' postProcessing/probes/0/U
sed -i 's/)//g' postProcessing/probes/0/U
gnuplot *.plt

echo '\033[1;92mGráficos criados usando o gnuplot.\033[0m\n'
gnuplot *.plt


