#!/bin/sh

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

echo "\n Construcao da geometria e malha usando o blockMesh. \n"
blockMesh

echo "\n Simulacao do escoamento usando o icoFoam. \n"
icoFoam > log

echo "\n Pos-Processamento do arquivo log.pisoFoam para analise da convergencia da solucao. \n"
foamLog log

echo "\n Pos-Processamento para coleta de dados para convergencia de malha. \n"
postProcess -func sample

gnuplot *.plt

