#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions


runApplication blockMesh
runApplication `getApplication`
foamLog log.pisoFoam
sed -i 's/(//g' postProcessing/force/0/forces.dat
sed -i 's/)//g' postProcessing/force/0/forces.dat
gnuplot *.plt
